name: Deploy Node Application

on: 
  push:
    branches:
      - tehmina

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: sudo docker build -t tehmina13/final-frontend_collective_freelance-marketplace --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}'  .
      - name: Publish Image to docker hub
        run: sudo docker push tehmina13/final-frontend_collective_freelance-marketplace:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull tehmina13/final-frontend_collective_freelance-marketplace:latest 
      - name: Delete old container
        run: sudo docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:80 --name reactjs-app-container tehmina13/final-frontend_collective_freelance-marketplace